/**
 * Plausibility test (E08-T3, docs/04 §2): "Token erscheint nie in Logs" -- the
 * bearer token must never leak into the pino log stream, whether supplied in a
 * request header, rejected as wrong, or freshly generated by the rotation
 * endpoint.
 */

import { describe, it, expect } from 'vitest';
import Fastify from 'fastify';
import { AuthGuard } from './authGuard.js';
import { authPlugin } from './plugin.js';

const TOKEN = 'super-secret-token-value-1234567890';

/** In-memory settings stub with the get/patch surface the auth plugin needs. */
function makeSettings(): { get(k: string): unknown; patch(v: Record<string, unknown>): Record<string, unknown>; store: Record<string, unknown> } {
  const store: Record<string, unknown> = {};
  return {
    store,
    get: (k) => store[k],
    patch: (v) => {
      Object.assign(store, v);
      return { ...store };
    },
  };
}

describe('token never appears in logs', () => {
  it('does not log the request token nor the generated token', async () => {
    const lines: string[] = [];
    const stream = { write: (s: string) => void lines.push(s) };
    const settings = makeSettings();
    const guard = new AuthGuard({ settings, env: { API_AUTH_TOKEN: TOKEN } });

    const fastify = Fastify({ logger: { level: 'trace', stream } });
    await fastify.register(authPlugin, { guard, settings });
    // A guarded route to exercise the hook.
    fastify.get('/api/v1/ping', async () => ({ ok: true }));
    await fastify.ready();

    // 1. Correct token in the header.
    await fastify.inject({
      method: 'GET',
      url: '/api/v1/ping',
      headers: { authorization: `Bearer ${TOKEN}` },
    });
    // 2. Wrong token -> 401 path.
    await fastify.inject({
      method: 'GET',
      url: '/api/v1/ping',
      headers: { authorization: 'Bearer definitely-wrong-value' },
    });
    // 3. Rotate: the response body carries a fresh token; it must not be logged.
    const rotate = await fastify.inject({
      method: 'POST',
      url: '/api/v1/auth/token',
      headers: { authorization: `Bearer ${TOKEN}` },
    });
    const generated = rotate.json().data.token as string;

    await fastify.close();

    const allLogs = lines.join('\n');
    expect(allLogs).not.toContain(TOKEN);
    expect(allLogs).not.toContain(generated);
  });
});
